### ISSUE TITLE
Remove interaction of search engine and creature description

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-database#1]
<img width="660" alt="Screenshot 2024-01-03 132450" src="https://github.com/BeneosBattlemaps/beneos-database/assets/106017284/5bf3d2b4-64a8-4398-b818-6d8a63653ae3">

The Search Engine searching for keywords within the creature's descriptions does more harm than good. Oftentimes there are more creatures displayed that have nothing to do with the actual search than relevant creatures (like the example visualised above).

**Comment by LeRatierBretonnien** [comment]
Done in module + search page

**Comment by LeRatierBretonnien** [comment]
PS : Better to post this on the module github itself instead of the database
