### ISSUE TITLE
Item Search: Results are not displayed even when directly searched for

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-database#2]
![WhatsApp Bild 2024-01-10 um 10 07 29_0fc39864](https://github.com/BeneosBattlemaps/beneos-database/assets/106017284/6301ed4c-72f3-40a8-aa9d-cefb12fe2028)
![WhatsApp Bild 2024-01-10 um 10 07 44_b5b7640b](https://github.com/BeneosBattlemaps/beneos-database/assets/106017284/e029e52f-4b6c-4d6f-9cc9-890b4caefcbc)

As you can see, both cloaks should be displayed as results for the "cloak" search but it shows "no result"

**Comment by LeRatierBretonnien** [comment]
Fixed
