### ISSUE TITLE
(Items) Sort some select fields manually instead of alphabetically

### ISSUE THREAD

**Issue by beneos-leon** [BeneosBattlemaps/beneos-database#4]
![WhatsApp Bild 2024-01-20 um 14 59 14_35a991b8](https://github.com/BeneosBattlemaps/beneos-database/assets/106017284/630c9e92-4fe3-4acb-8413-5ac6e185ec0d)

The "Rarity" and "Price" selection fields should be sorted in a logical sense, instead of alphabtetically.

Rarity:
Common -> Uncommon -> Rare -> Very Rare -> Legendary

Price: <100 - <1000  - <5000 - <15 000 - >15000

**Comment by LeRatierBretonnien** [comment]
Specific cases for rarity+price added in both module and search page.
